# Generated by Django 3.0.5 on 2020-04-19 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('SLP', 'Sleep'), ('DDM', 'Daydream'), ('PSY', 'Psychedelic')], default='SLP', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
