# Generated by Django 3.0.5 on 2020-04-20 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='label',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dream',
            name='registered_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
