# Generated by Django 3.0.5 on 2020-04-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_auto_20200420_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='registered_at',
            new_name='transcripted_at',
        ),
    ]
