# Generated by Django 3.0.5 on 2020-04-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_auto_20200423_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='label',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
