# Generated by Django 3.0.5 on 2020-04-26 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreams', '0004_auto_20200426_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='body',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='label',
        ),
        migrations.AddField(
            model_name='dream',
            name='text',
            field=models.TextField(blank=True, verbose_name='dream content'),
        ),
        migrations.AddField(
            model_name='dream',
            name='title',
            field=models.CharField(blank=True, max_length=25, verbose_name='title or identifying label'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='soft_deleted',
            field=models.BooleanField(default=False, verbose_name='In the trash bin'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='transcripted_at',
            field=models.DateField(blank=True, null=True, verbose_name='transcription date'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='type',
            field=models.CharField(choices=[('SLP', 'Sleep'), ('DDM', 'Daydream'), ('PSY', 'Psychedelic'), ('OTH', 'Other')], default='SLP', max_length=3, verbose_name='dream type'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='dreamer'),
        ),
    ]
