# Generated by Django 3.0.5 on 2020-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='span',
            field=models.CharField(blank=True, help_text='Two comma-separated numbers describing             start/stop position in original string', max_length=25),
        ),
    ]
