# Generated by Django 3.0.5 on 2020-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_artefact_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='type',
            field=models.CharField(choices=[('OBS', 'Observation'), ('FRS', 'Freudian slip'), ('SYM', 'Symbols')], default='OBS', max_length=3),
        ),
    ]
