# Generated by Django 3.0.5 on 2020-04-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_auto_20200426_0014'),
        ('artefacts', '0004_auto_20200425_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream'),
        ),
    ]
