# Generated by Django 3.0.5 on 2020-04-26 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0005_auto_20200426_1923'),
        ('artefacts', '0005_auto_20200426_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreudianSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False, verbose_name='In the trash bin')),
                ('meant', models.CharField(blank=True, max_length=255, verbose_name='what was meant')),
                ('slipped', models.CharField(blank=True, max_length=255, verbose_name='slipped')),
                ('snippet_start', models.IntegerField(default=0, editable=False, verbose_name='Start position in original text')),
                ('snippet_end', models.IntegerField(default=0, editable=False, verbose_name='End position in original text')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream', verbose_name='dream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False, verbose_name='In the trash bin')),
                ('text', models.TextField(blank=True)),
                ('snippet_start', models.IntegerField(default=0, verbose_name='Start position in original text')),
                ('snippet_end', models.IntegerField(default=0, verbose_name='End position in original text')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Artefact',
        ),
    ]
