# Generated by Django 3.0.5 on 2020-04-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_auto_20200428_2243'),
        ('artefacts', '0006_auto_20200426_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freudianslip',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='dreams.Dream', verbose_name='dream'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dreams.Dream'),
        ),
    ]
