# Generated by Django 3.0.5 on 2020-04-19 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True)),
                ('dream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
