# Generated by Django 3.0.5 on 2020-04-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0005_auto_20200426_1923'),
        ('interpretations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='body',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='text',
            field=models.TextField(blank=True, verbose_name='interpretation'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='dream',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream', verbose_name='dream'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='soft_deleted',
            field=models.BooleanField(default=False, verbose_name='In the trash bin'),
        ),
    ]
